name: Solidity unit test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make .env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_SIGNER_PRIVATE_KEY: ${{ secrets.COOKIE_NAME }}
          directory: '../../'
          file_name: '.env'
          fail_on_empty: true
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install node modules
        run: npm ci
      - name: Unit test solidity
        run: npx hardhat test